### ISSUE TITLE
Sealed simulator doesn't work with variable size packs

### ISSUE THREAD

**Issue by axxroytovu** [taw/magic-search-engine#173] opened 2023-04-05 02:13 UTC
I have no idea if this is even something we want to support, but the current code for sealed simulator doesn't support packs with variable size (like set boosters).

https://mtg.wtf/sealed?count%5B%5D=1&set%5B%5D=one-set - doesn't work
https://mtg.wtf/sealed?count%5B%5D=1&set%5B%5D=one-collector - does work

**Comment by taw** [comment] 2023-04-05 08:32
This is not the problem. The problem is "Can't color balance 3 for one".

**Comment by taw** [comment] 2023-04-05 09:14
The error message is not very specific, as it could be one of two problems:

* color balancing was requested for very small number of cards - it's never correct, and should be caught by indexer for better error message
* color balancing was requested for reasonable number of cards, but the set has unbalanced color identity on commons (usually due to too many multicolor cards) - that's why the warning is dynamically there

It should be off for everything except draft common sheet.

Sets with variable size packs are supported just fine. Technically M19 draft boosters were like that (if DFC in the pack, then DFC checklist instead of land), but I didn't implement that rule.

**Comment by taw** [comment] 2023-04-05 09:17
Issue fixed with https://github.com/taw/magic-search-engine/commit/ef86fd0ae56436a4d24d2361276a66a9ddeb63e5

I'll add better error handling later.

**Closed by taw** 2023-04-05 09:17 UTC
