### ISSUE TITLE
Eldraine images missing

### ISSUE THREAD

**Issue by glaebhoerl** [taw/magic-search-engine#155] opened 2022-07-16 11:17 UTC
[set:eld view:images](https://mtg.wtf/card?q=set%3Aeld+view%3Aimages)

I don't know if this affects *just* Eldraine but it does seem to affect all of it.

**Comment by taw** [comment] 2022-07-16 11:59
Thanks. Looks like the script to link the pics had a bug. Fixed now.

**Comment by taw** [comment] 2022-07-16 12:27
I checked all remaining pictures, and other than Eldraine, there was another issue where 28 missing pictures from some promo sets were missing.

The promo issue was caused by mtgjson changing card number's case (from `2019NA` to `2019na` etc.). As I develop on OSX, which is case-insensitive, these were all reported as still having proper pictures, but then Linux server couldn't find them due to case mismatch. All these are fixed now, but they could still happen in the future.

**Closed by taw** 2022-07-16 12:27 UTC
